# ---- Build Stage ----
FROM eclipse-temurin:25-jdk-alpine AS build

WORKDIR /app

# Копируем Gradle wrapper
COPY gradlew .
COPY gradle gradle
RUN chmod +x gradlew

# Копируем корневые конфигурации
COPY build.gradle .
COPY settings.gradle .

# Копируем ВСЕ модули (чтобы Gradle не ругался)
COPY common common
COPY loom loom
COPY reactor reactor
COPY application-loom application-loom
COPY application-reactor application-reactor

# Собираем Loom приложение с флагом skipJooq
RUN ./gradlew :application-loom:bootJar -x test -PskipJooq

# ---- Run Stage ----
FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

COPY --from=build /app/application-loom/build/libs/*.jar app.jar

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
