# ---- Build Stage ----
FROM eclipse-temurin:25-jdk AS build

WORKDIR /workspace

# Копируем всё
COPY . .

# Даем права на выполнение gradlew
RUN chmod +x gradlew

# Собираем Loom приложение
RUN ./gradlew :application-loom:bootJar --no-daemon -x test -PskipJooq

# ---- Run Stage ----
FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build /workspace/application-loom/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
